/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f4faff",
        "on-surface": "#0d1e25",
        "surface-container-low": "#e7f6ff",
        "surface-container-high": "#d9ebf5",
        "surface-container-highest": "#d4e5ef",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#dff1fb",
        "surface-tint": "#004ee8",
        "on-primary": "#ffffff",
        "on-surface-variant": "#454652",
        "outline": "#767683",
        "outline-variant": "#c6c5d4",
        "primary": "#00154f",
        "primary-container": "#00267e",
        "tertiary": "#380b00",
        "tertiary-container": "#5c1800",
        "on-tertiary-fixed-variant": "#7b2e12",
        "on-tertiary-container": "#e17c5a",
        "tertiary-fixed": "#ffdbd0",
        "on-primary-container": "#7391ff",
        "secondary-fixed-dim": "#bbc6e2",
        "on-secondary-fixed-variant": "#3c475d",
        "surface-variant": "#d4e5ef",
        "surface-bright": "#f4faff",
        "inverse-surface": "#23333a",
        "error": "#ba1a1a",
        "secondary": "#545e76",
        "inverse-on-surface": "#e2f3fd",
        "background": "#f4faff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#101b30",
        "primary-fixed-dim": "#b6c4ff",
        "on-error": "#ffffff",
        "on-background": "#0d1e25",
        "on-primary-fixed-variant": "#003ab3",
        "inverse-primary": "#b6c4ff",
        "on-secondary-container": "#5a647c",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "surface-dim": "#cbdde7",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d7e2ff",
        "on-primary-fixed": "#001550",
        "tertiary-fixed-dim": "#ffb59d",
        "secondary-fixed": "#d7e2ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
